
export const STORAGE_KEYS = {
  ACCOUNTS: 'localeAppAccounts',
  CURRENT_ACCOUNT_ID: 'localeAppCurrentAccountId',
  USER_DATA: 'localeAppAllUsersData',
  USER_ACTIVITY_DATA: 'localeAppUserActivityData',
  POSTS: 'localeAppPosts',
  ARCHIVED_POSTS: 'localeAppArchivedPosts',
  CATEGORIES: 'localeAppCategories',
  PRICE_UNITS: 'localeAppPriceUnits',
  FORUM_POSTS: 'localeAppForumPosts',
  FORUM_COMMENTS: 'localeAppForumComments',
  FORUM_CATEGORIES: 'localeAppForumCategories',
  FILTERS: 'localeAppFilters',
  RECENT_SEARCHES: 'localeAppRecentSearches',
  SAVED_SEARCHES: 'localeAppSavedSearches',
  GRID_VIEW: 'localeAppGridView',
  REPORTS: 'localeAppReports',
  FEEDBACK: 'localeAppFeedback',
  TERMS: 'localeAppTermsContent',
  PRIVACY: 'localeAppPrivacyContent',
  GEOCODING_CACHE: 'localeGeocodingCache',
  MAP_STATE: 'localeMapViewState',
  POST_DRAFT: 'locale_post_draft_v2',
  GUEST_PROMPT: 'localeGuestPromptDismissed',
  MEDIA_CAROUSEL_PREFIX: 'media-carousel-state-',
  STORY_POSTS: 'localeAppStoryPosts',
};